server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service # 应用名称
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
mybatis:
  type-aliases-package: cn.itheima.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itheima: debug




